"use client";

import { useState } from "react";

import type { PlayInteraction } from "@/content/client";
import InteractionPlayer from "@/interactions/InteractionPlayer";

/**
 * Playing one rung at a time, in the real player.
 *
 * The only thing this component adds to what a child would see is the ability
 * to jump between classes and to read the authored JSON underneath — both of
 * which are for the person judging the ladder, not for anybody using the
 * product. Everything inside the player is untouched: same assistance rungs,
 * same Halo, same celebration, same manners.
 *
 * It renders nothing at all in a production build. `process.env.NODE_ENV` is
 * replaced with a literal at build time, so this is dead code in production
 * and the bundler drops it along with the ladder it imports.
 */

export type Rung = {
  id: string;
  display: string;
  skipped: string | null;
  steps: { authored: Record<string, unknown>; played: PlayInteraction }[];
};

export default function LadderPreview({
  rungs,
  verse,
  from,
}: {
  rungs: Rung[];
  verse: { text: string; reference: string };
  from: string;
}) {
  const [at, setAt] = useState(0);
  const [step, setStep] = useState(0);
  const [round, setRound] = useState(0);
  const [showJson, setShowJson] = useState(false);

  if (process.env.NODE_ENV === "production") return null;

  const rung = rungs[at];
  if (!rung) return null;

  const current = rung.steps[step];

  function go(next: number) {
    setAt(next);
    setStep(0);
    setRound((r) => r + 1);
  }

  return (
    <main className="mx-auto flex max-w-2xl flex-col gap-6 px-6 py-10">
      <header className="flex flex-col gap-2">
        <p className="text-xs tracking-[0.14em] text-ink-soft uppercase">
          Dev · memory verse ladder
        </p>
        <h1 className="text-3xl leading-tight">Nursery → Young Adult</h1>
        <p className="text-base text-ink-soft text-balance">
          One verse, seven ways of asking for it back. Generated by
          <code className="mx-1">agents/memory-verse</code>
          from the verse in <code>{from}</code>.
        </p>
        <p className="mt-1 text-base leading-relaxed text-balance text-joy">
          {verse.text}
        </p>
        <p className="text-sm text-ink-soft">{verse.reference}</p>
      </header>

      {/* Which rung. Ordered youngest to oldest, which is the whole claim. */}
      <ul className="grid grid-cols-2 gap-2">
        {rungs.map((r, i) => (
          <li key={r.id} className="flex">
            <button
              type="button"
              onClick={() => go(i)}
              aria-pressed={i === at}
              className={`surface flex min-h-12 flex-1 items-center justify-center px-3 text-base ${
                i === at ? "surface-lit" : ""
              } ${r.skipped ? "opacity-50" : ""}`}
            >
              {i + 1}. {r.display}
            </button>
          </li>
        ))}
      </ul>

      <div className="flex flex-col gap-2 border-t border-edge pt-5">
        <p className="text-sm text-ink-soft">
          {rung.display} ·{" "}
          {rung.skipped
            ? "not generated"
            : rung.steps.map((s) => String(s.played.type)).join(" → ")}
          {rung.steps.length > 1 ? ` · step ${step + 1} of ${rung.steps.length}` : ""}
        </p>

        {rung.skipped ? (
          <p className="py-8 text-center text-lg text-ink-soft text-balance">
            {rung.skipped}
          </p>
        ) : current ? (
          <div className="flex flex-col items-center gap-4 py-4">
            <InteractionPlayer
              key={`${rung.id}-${step}-${round}`}
              interaction={current.played}
              onComplete={() => {
                if (step + 1 < rung.steps.length) {
                  window.setTimeout(() => setStep(step + 1), 1400);
                }
              }}
            />

            <button
              type="button"
              onClick={() => setRound((r) => r + 1)}
              className="btn-quiet min-h-12 px-5 text-base"
            >
              Play it again
            </button>
          </div>
        ) : null}
      </div>

      <div className="flex flex-col gap-2 border-t border-edge pt-5">
        <button
          type="button"
          onClick={() => setShowJson((was) => !was)}
          className="self-start text-base text-ink-soft underline underline-offset-4"
        >
          {showJson ? "Hide" : "Show"} what the agent wrote
        </button>

        {showJson ? (
          <pre className="overflow-x-auto rounded-card bg-ground-raised p-4 text-xs leading-relaxed text-ink-soft">
            {JSON.stringify(rung.steps.map((s) => s.authored), null, 2)}
          </pre>
        ) : null}
      </div>
    </main>
  );
}
